# Generated by Django 4.1 on 2022-09-05 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeanDropProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beandrop_qr_generator', models.CharField(default='', editable=False, max_length=100)),
                ('beandrop_user_funds', models.IntegerField(default=0, editable=False)),
                ('beandrop_cups_in_ownership', models.IntegerField(default=0, editable=False)),
                ('beandrop_number_of_cups_used', models.IntegerField(default=0, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
