# Generated by Django 4.1.2 on 2022-11-04 11:25

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('users', 'Profile')
    for row in MyModel.objects.all():
        row.beandrop_social_user_uuid = uuid.uuid4()
        row.save(update_fields=['beandrop_social_user_uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registered_users_db_users_db_and_more'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
