# Generated by Django 4.1 on 2022-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pics'),
        ),
    ]
